//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm.Models
{
    using System;
    using System.Collections.Generic; 
    
    public partial class Person
    {
        public int TableId { get; set; }
        public int DepId { get; set; }
        public string PersonName { get; set; }
        public System.DateTime EntryTime { get; set; }
        public System.DateTime TurnoverTime { get; set; }
        public int Status { get; set; }
        public string WebUserName { get; set; }
        public int GangWeiId { get; set; }
        public string WebPassword { get; set; }
        public int JinDieFUserID { get; set; }
        public string QQAuthOpenId { get; set; }
        public string QQAuthUserAccount { get; set; }
        public int FenXiaoId { get; set; }
        public string pageIndex { get; set; }
    }
}
